#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {[0] = LAYOUT(KC_KP_9, KC_NUM, KC_NO, KC_SCRL, KC_PSCR, KC_F12, KC_F10, KC_F9, KC_F7, KC_F6, KC_F5, KC_F4, KC_F3, KC_F2, KC_F1, KC_ESC,
    KC_KP_SLASH, KC_KP_EQUAL, KC_KP_8, KC_PAUSE, KC_PGUP, KC_BSPC, KC_F11, KC_0, KC_F8, KC_7, KC_6, KC_4, KC_3, KC_2, KC_1, KC_TILDE,
    KC_KP_ASTERISK, KC_NO, KC_KP_7, KC_NO, KC_PGDN, KC_BSLASH, KC_EQUAL, KC_O, KC_9, KC_8, KC_T, KC_5, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_KP_MINUS, KC_NO, KC_KP_6, KC_NO, KC_END, KC_HOME, KC_LBRC, KC_MINS, KC_NO, KC_NO, KC_Y, KC_G, KC_NO, KC_NO, KC_NO, KC_NO,
    KC_KP_3, KC_RIGHT, KC_KP_5, KC_NO, KC_DEL, KC_INS, KC_RBRC, KC_P, KC_K, KC_I, KC_NO, KC_R, KC_E, KC_W, KC_Q, KC_TAB,
    KC_KP_ENTER, KC_NO, KC_KP_4, KC_NO, KC_UP, KC_ENTER, KC_QUOT, KC_SCLN, KC_L, KC_NO, KC_U, KC_NO, KC_D, KC_NO, KC_NO, KC_NO,
    KC_NO, KC_NO, KC_KP_PLUS, KC_LEFT, KC_NO, KC_DOT, KC_SLSH, KC_COMM, KC_J, KC_H, KC_B, KC_F, KC_NO, KC_NO, KC_S, KC_A,
    KC_NO, KC_KP_DOT, KC_NO, KC_DOWN, KC_KP_2, KC_KP_1, KC_KP_0, KC_M, KC_N, KC_NO, KC_SPACE, KC_V, KC_C, KC_X, KC_Z, KC_NO)};
